// Convert a research report into Markdown / plain text and trigger downloads.

export function reportToMarkdown(report) {
  if (!report) return "";
  const lines = [];
  lines.push(`# ${report.query}`);
  lines.push("");
  lines.push(`*Generated by NeuroScout AI · ${new Date(report.created_at).toLocaleString()} · ${report.search_iterations} search iterations · ${report.generation_time_sec}s*`);
  lines.push("");
  lines.push("## Executive Summary");
  lines.push("");
  lines.push(report.executive_summary || "");
  lines.push("");
  (report.sections || []).forEach((s) => {
    lines.push(`## ${s.heading}`);
    lines.push("");
    lines.push(s.content || "");
    lines.push("");
  });
  if ((report.key_takeaways || []).length > 0) {
    lines.push("## Key Takeaways");
    lines.push("");
    (report.key_takeaways || []).forEach((t) => {
      lines.push(`- ${t}`);
    });
    lines.push("");
  }
  lines.push("## References");
  lines.push("");
  (report.references || []).forEach((r) => {
    lines.push(`${r.id}. [${r.title}](${r.url}) — accessed ${new Date(r.accessed_date).toLocaleDateString()}`);
  });
  return lines.join("\n");
}

export function reportToText(report) {
  return reportToMarkdown(report)
    .replace(/^#+\s+/gm, "")
    .replace(/\*\*/g, "")
    .replace(/\*/g, "")
    .replace(/\[(.+?)\]\((.+?)\)/g, "$1 ($2)");
}

export function downloadFile(filename, content, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
